version: "3.1"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE=mongodb://db:27017
  db:
    # Use the image from MongoDB
    image: mongo:latest
    # Define Image name
    environment:
      MONGO_INITDB_DATABASE: myapp
    # port where find mongo
    ports:
      - 27017:27017
